name: Create Daily Issue

on:
  schedule:
    - cron: '0 0 * * *' # 毎日UTC時間0時に実行
  workflow_dispatch: # 手動でアクションをトリガーするための設定

jobs:
  create_issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_owner=${{ github.repository_owner }}
          repo_name=${{ github.event.repository.name }}
          issue_title="Daily Issue - $(date +\%Y-\%m-\%d)"
          issue_body="This is a daily issue created by a GitHub Action."
          
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title":"'"$issue_title"'","body":"'"$issue_body"'"}' \
            "https://api.github.com/repos/$repo_owner/$repo_name/issues"
