name: Create Monthly PR

on:
  schedule:
    - cron: '0 0 1 * *' # 毎月1日UTC時間0時に実行
  workflow_dispatch: # 手動でアクションをトリガーするための設定

jobs:
  create_pr:
    runs-on: ubuntu-latest

    # permissions:
    #   pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.email "hikeuchi@morisawa.co.jp"
          git config --global user.name "hikeuchi"

      - name: Create Monthly PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_owner=${{ github.repository_owner }}
          repo_name=${{ github.event.repository.name }}
          branch_name="feature/update-library/$(date +\%Y\%m\%d)"
          pr_title="Daily PR - $(date +\%Y-\%m-\%d)"
          pr_body="Poetryのアップデートを行ってください\n\n- [ ] poetryの更新\n\n```sh\ncd <path-to-dir>\npoetry update\n# 更新されたpoetry.lockをコミット\n```\n\n- [ ] 全テストを実行し動作に問題ないかの確認"

          git checkout -b $branch_name
          git commit --allow-empty -m "Monthly commit"
          git push origin $branch_name
          
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title":"'"$pr_title"'","body":"'"$pr_body"'","head":"'"$branch_name"'","base":"main"}' \
            "https://api.github.com/repos/$repo_owner/$repo_name/pulls"
