name: Create Daily PR

on:
  schedule:
    - cron: '0 0 * * *' # 毎日UTC時間0時に実行
  workflow_dispatch: # 手動でアクションをトリガーするための設定

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Daily PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_owner=${{ github.repository_owner }}
          repo_name=${{ github.event.repository.name }}
          branch_name="feature/update-library/$(date +\%Y\%m\%d)"
          pr_title="Daily PR - $(date +\%Y-\%m-\%d)"
          pr_body="This is a daily PR created by a GitHub Action."
          
          git checkout -b $branch_name
          git commit --allow-empty -m "Daily commit"
          git push origin $branch_name
          
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title":"'"$pr_title"'","body":"'"$pr_body"'","head":"'"$branch_name"'","base":"main"}' \
            "https://api.github.com/repos/$repo_owner/$repo_name/pulls"
