name: Create Poetry Monthly Update  PR

on:
  schedule:
    - cron: '0 0 1 * *' # 毎月1日UTC時間0時に実行
  workflow_dispatch: # 手動でアクションをトリガーするための設定

jobs:
  create_pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      # Permissionの確認(https://github.com/GitHubSecurityLab/actions-permissions)
      # - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      #   with:
      #     config: ${{ vars.PERMISSIONS_CONFIG }}
    
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.email "hikeuchi@morisawa.co.jp"
          git config --global user.name "hikeuchi"

      - name: Create Monthly PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Asia/Tokyo
        run: |
          repo_owner=${{ github.repository_owner }}
          repo_name=${{ github.event.repository.name }}
          branch_name="feature/update-library/$(date +\%Y\%m\%d-\%H\%M\%S)"
          pr_title="Poetryのアップデート(月次) - $(date +\%Y年%m月)"
          pr_body="Poetryのアップデートを行ってください\\n\\n- [ ] poetryの更新\\n\\n\`\`\`sh\\ncd <path-to-dir>\\npoetry update\\n# 更新されたpoetry.lockをコミット\\n\`\`\`\\n\\n- [ ] 全テストを実行し動作に問題ないかの確認"
          assignees='["hikeuchi"]'
          # reviewers='["reviewer1", "reviewer2"]'

          git checkout -b $branch_name
          git commit --allow-empty -m "chore: Poetryの更新"
          git push origin $branch_name
          
          pr_id=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"title\":\"$pr_title\",\"body\":\"$pr_body\",\"head\":\"$branch_name\",\"base\":\"main\"}" \
            "https://api.github.com/repos/$repo_owner/$repo_name/pulls" | jq '.number')

          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"assignees\": $assignees}" \
            "https://api.github.com/repos/$repo_owner/$repo_name/issues/$pr_id/assignees"

          # curl -X POST \
          #   -H "Authorization: token $GITHUB_TOKEN" \
          #   -d "{\"reviewers\": $reviewers}" \
          #   "https://api.github.com/repos/$repo_owner/$repo_name/pulls/$pr_id/requested_reviewers"
