name: Flake8 Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          # ignore: "F401"
          # exclude: "src/ignoreme.py"
          max-line-length: "79"
          # path: "src"
          plugins: "flake8-bugbear==22.1.11 flake8-black"
          args: "--max-complexity=10"
