name: Lint Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"     

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install mypy
          pip install black
          pip install isort

      # Flake8
      - name: Rum Flake8
        run: flake8 .
      
      # Mypy
      - name: Run Mypy
        run: mypy .

      # Black_Formatter
      - name: Run Black_Formatter
        run: black . --check

      # isort
      - name: Run isort
        run: isort . -c
