name: Mypy-Checker Check

on:
  pull_request:
    path:
      - '*.py'
  workflow_dispatch:
    path:
      - '*.py'
jobs:
  mypy:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
          args: "--ignore-missing-imports --disallow-untyped-defs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
